<?php 
defined( 'ABSPATH' ) or die( 'No script kiddies please!' );
/**
 * danixland-contact-form standard Template
 * Template Name = danixland
 * Template Author = danilo 'danix' macri
 * Template URI = http://danixland.net
 */

/*
This templating system is really simple, it makes use of a filter inside the
main file that allows template developers to create and use different templates
for their emails simply by hooking to the filter without the need to modify the
original files. It's perfect for customers who want a consistent look between
the website and the emails.

The template file itself consist of a function that receives arrays as
arguments and returns some formatted html as output.

The data received by the template consists of 2 different arrays containing the
info that will be reported inside the email sent by the contact form.
the 2 arrays example structure is the following:

// this is data gathered via various php variables and WordPress functions
$data = array(
    'ownname'   = '', // name of the person receiving the message aka US!
    'site'      = get_bloginfo('name'), // the site name
    'time'      = '', // string generated by current_time()
    'host'      = '', // string generated by getenv("REMOTE_ADDR")
    'ua'        = ''  // string corresponding to $_SERVER['HTTP_USER_AGENT']
);

// this is data sent via $_POST by the form itself
$posted = array(
    'dnxcf_name'    = '', // the name of the user sending the message
    'dnxcf_email'   = '', // the user's email
    'dnxcf_website' = '', // the user's website
    'dnxcf_subject' = '', // the subject of the message
    'dnxcf_message' = ''  // the message body
);

*/

// this is the main function, it returns the email content and needs to have
// always the same name or the main plugin won't be able to send emails
// NOTE TO SELF: "I need to fix this ASAP"
function dnxcf_email_content( $data = array(), $posted = array() ) {
    extract($data);
    extract($posted);

    $ownurl = get_bloginfo('url');
// heredoc to return the email content
    $output = <<<DNX44665312EOT

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<meta name="viewport" content="width=device-width"/>
<style>
    #outlook a {
        padding: 0;
    }
    body {
        background-color: #eaeaea;
        width: 100%!important;
        min-width: 100%;
        -webkit-text-size-adjust: 100%;
        -ms-text-size-adjust: 100%;
        margin: 0;
        padding: 0;
    }
    .ExternalClass {
        width: 100%;
    }
    .ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div {
        line-height: 100%;
    }
    #backgroundTable {
        margin: 0;
        padding: 0;
        width: 100%!important;
        line-height: 100%!important;
    }
    img {
        outline: none;
        text-decoration: none;
        -ms-interpolation-mode: bicubic;
        width: auto;
        max-width: 100%;
        float: left;
        clear: both;
        display: block;
    }
    center {
        width: 100%;
        min-width: 580px;
    }
    a img {
        border: none;
    }
    p {
        margin: 0 0 0 10px;
    }
    table {
        border-spacing: 0;
        border-collapse: collapse;
    }
    td {
        word-break: break-word;
        -webkit-hyphens: auto;
        -moz-hyphens: auto;
        hyphens: auto;
        border-collapse: collapse!important;
    }
    table, tr, td {
        padding: 0;
        vertical-align: top;
        text-align: left;
    }
    hr {
        color: #d9d9d9;
        background-color: #d9d9d9;
        height: 1px;
        border: none;
    }
    table.body {
        height: 100%;
        width: 100%;
    }
    table.container {
        width: 580px;
        margin: 0 auto;
        text-align: inherit;
    }
    table.row {
        padding: 0px;
        width: 100%;
        position: relative;
    }
    table.container table.row {
        display: block;
    }
    td.wrapper {
        padding: 10px 20px 0px 0px;
        position: relative;
    }
    table.columns, table.column {
        margin: 0 auto;
    }
    table.columns td, table.column td {
        padding: 0px 0px 10px;
    }
    table.columns td.sub-columns, table.column td.sub-columns, table.columns td.sub-column, table.column td.sub-column {
        padding-right: 10px;
    }
    td.sub-column, td.sub-columns {
        min-width: 0px;
    }
    table.row td.last, table.container td.last {
        padding-right: 0px;
    }
    table.one {
        width: 30px;
    }
    table.two {
        width: 80px;
    }
    table.three {
        width: 130px;
    }
    table.four {
        width: 180px;
    }
    table.five {
        width: 230px;
    }
    table.six {
        width: 280px;
    }
    table.seven {
        width: 330px;
    }
    table.eight {
        width: 380px;
    }
    table.nine {
        width: 430px;
    }
    table.ten {
        width: 480px;
    }
    table.eleven {
        width: 530px;
    }
    table.twelve {
        width: 580px;
    }
    table.one center {
        min-width: 30px;
    }
    table.two center {
        min-width: 80px;
    }
    table.three center {
        min-width: 130px;
    }
    table.four center {
        min-width: 180px;
    }
    table.five center {
        min-width: 230px;
    }
    table.six center {
        min-width: 280px;
    }
    table.seven center {
        min-width: 330px;
    }
    table.eight center {
        min-width: 380px;
    }
    table.nine center {
        min-width: 430px;
    }
    table.ten center {
        min-width: 480px;
    }
    table.eleven center {
        min-width: 530px;
    }
    table.twelve center {
        min-width: 580px;
    }
    table.one .panel center {
        min-width: 10px;
    }
    table.two .panel center {
        min-width: 60px;
    }
    table.three .panel center {
        min-width: 110px;
    }
    table.four .panel center {
        min-width: 160px;
    }
    table.five .panel center {
        min-width: 210px;
    }
    table.six .panel center {
        min-width: 260px;
    }
    table.seven .panel center {
        min-width: 310px;
    }
    table.eight .panel center {
        min-width: 360px;
    }
    table.nine .panel center {
        min-width: 410px;
    }
    table.ten .panel center {
        min-width: 460px;
    }
    table.eleven .panel center {
        min-width: 510px;
    }
    table.twelve .panel center {
        min-width: 560px;
    }
    .body .columns td.one, .body .column td.one {
        width: 8.333333%;
    }
    .body .columns td.two, .body .column td.two {
        width: 16.666666%;
    }
    .body .columns td.three, .body .column td.three {
        width: 25%;
    }
    .body .columns td.four, .body .column td.four {
        width: 33.333333%;
    }
    .body .columns td.five, .body .column td.five {
        width: 41.666666%;
    }
    .body .columns td.six, .body .column td.six {
        width: 50%;
    }
    .body .columns td.seven, .body .column td.seven {
        width: 58.333333%;
    }
    .body .columns td.eight, .body .column td.eight {
        width: 66.666666%;
    }
    .body .columns td.nine, .body .column td.nine {
        width: 75%;
    }
    .body .columns td.ten, .body .column td.ten {
        width: 83.333333%;
    }
    .body .columns td.eleven, .body .column td.eleven {
        width: 91.666666%;
    }
    .body .columns td.twelve, .body .column td.twelve {
        width: 100%;
    }
    td.offset-by-one {
        padding-left: 50px;
    }
    td.offset-by-two {
        padding-left: 100px;
    }
    td.offset-by-three {
        padding-left: 150px;
    }
    td.offset-by-four {
        padding-left: 200px;
    }
    td.offset-by-five {
        padding-left: 250px;
    }
    td.offset-by-six {
        padding-left: 300px;
    }
    td.offset-by-seven {
        padding-left: 350px;
    }
    td.offset-by-eight {
        padding-left: 400px;
    }
    td.offset-by-nine {
        padding-left: 450px;
    }
    td.offset-by-ten {
        padding-left: 500px;
    }
    td.offset-by-eleven {
        padding-left: 550px;
    }
    td.expander {
        visibility: hidden;
        width: 0px;
        padding: 0!important;
    }
    table.columns .text-pad, table.column .text-pad {
        padding-left: 10px;
        padding-right: 10px;
    }
    table.columns .left-text-pad, table.columns .text-pad-left, table.column .left-text-pad, table.column .text-pad-left {
        padding-left: 10px;
    }
    table.columns .right-text-pad, table.columns .text-pad-right, table.column .right-text-pad, table.column .text-pad-right {
        padding-right: 10px;
    }
    .block-grid {
        width: 100%;
        max-width: 580px;
    }
    .block-grid td {
        display: inline-block;
        padding: 10px;
    }
    .two-up td {
        width: 270px;
    }
    .three-up td {
        width: 173px;
    }
    .four-up td {
        width: 125px;
    }
    .five-up td {
        width: 96px;
    }
    .six-up td {
        width: 76px;
    }
    .seven-up td {
        width: 62px;
    }
    .eight-up td {
        width: 52px;
    }
    table.center, td.center {
        text-align: center;
    }
    h1.center, h2.center, h3.center, h4.center, h5.center, h6.center {
        text-align: center;
    }
    span.center {
        display: block;
        width: 100%;
        text-align: center;
    }
    img.center {
        margin: 0 auto;
        float: none;
    }
    .show-for-small, .hide-for-desktop {
        display: none;
    }
    body, table.body, h1, h2, h3, h4, h5, h6, p, td {
        color: #222222;
        font-family: "Helvetica", "Arial", sans-serif;
        font-weight: normal;
        padding: 0;
        margin: 0;
        text-align: left;
        line-height: 1.3;
    }
    h1, h2, h3, h4, h5, h6 {
        word-break: normal;
    }
    h1 {
        font-size: 40px;
    }
    h2 {
        font-size: 36px;
    }
    h3 {
        font-size: 32px;
    }
    h4 {
        font-size: 28px;
    }
    h5 {
        font-size: 24px;
    }
    h6 {
        font-size: 20px;
    }
    body, table.body, p, td {
        font-size: 14px;
        line-height: 19px;
    }
    p.lead, p.lede, p.leed {
        font-size: 18px;
        line-height: 21px;
    }
    p {
        margin-bottom: 10px;
        text-align: justify;
    }
    small {
        font-size: 10px;
    }
    a {
        color: #387c2b;
        text-decoration: none;
    }
    a:hover {
        color: #faa634!important;
    }
    a:active {
        color: #faa634!important;
    }
    a:visited {
        color: #387c2b!important;
    }
    h1 a, h2 a, h3 a, h4 a, h5 a, h6 a {
        color: #387c2b;
    }
    h1 a:active, h2 a:active, h3 a:active, h4 a:active, h5 a:active, h6 a:active {
        color: #387c2b!important;
    }
    h1 a:visited, h2 a:visited, h3 a:visited, h4 a:visited, h5 a:visited, h6 a:visited {
        color: #387c2b!important;
    }
    .panel { /* PANNELLO AZZURRINO */
        background: #cbcbcb;
        border: 1px solid #d9d9d9;
        padding: 10px!important;
        box-shadow: 1px 3px 12px rgba(120,120,120,0.6);
    }
    .sub-grid table {
        width: 100%;
    }
    .sub-grid td.sub-columns {
        padding-bottom: 0;
    }
    table.button, table.tiny-button, table.small-button, table.medium-button, table.large-button {
        width: 100%;
        overflow: hidden;
    }
    table.button td, table.tiny-button td, table.small-button td, table.medium-button td, table.large-button td {
        display: block;
        width: auto!important;
        text-align: center;
        background: #387c2b;
        border: 1px solid #2284a1;
        color: #ffffff;
        padding: 8px 0;
    }
    table.tiny-button td {
        padding: 5px 0 4px;
    }
    table.small-button td {
        padding: 8px 0 7px;
    }
    table.medium-button td {
        padding: 12px 0 10px;
    }
    table.large-button td {
        padding: 21px 0 18px;
    }
    table.button td a, table.tiny-button td a, table.small-button td a, table.medium-button td a, table.large-button td a {
        font-weight: bold;
        text-decoration: none;
        font-family: Helvetica, Arial, sans-serif;
        color: #ffffff;
        font-size: 16px;
    }
    table.tiny-button td a {
        font-size: 12px;
        font-weight: normal;
    }
    table.small-button td a {
        font-size: 16px;
    }
    table.medium-button td a {
        font-size: 20px;
    }
    table.large-button td a {
        font-size: 24px;
    }
    table.button:hover td, table.button:visited td, table.button:active td {
        background: #faa634!important;
    }
    table.button:hover td a, table.button:visited td a, table.button:active td a {
        color: #fff!important;
    }
    table.button:hover td, table.tiny-button:hover td, table.small-button:hover td, table.medium-button:hover td, table.large-button:hover td {
        background: #faa634!important;
    }
    table.button:hover td a, table.button:active td a, table.button td a:visited, table.tiny-button:hover td a, table.tiny-button:active td a, table.tiny-button td a:visited, table.small-button:hover td a, table.small-button:active td a, table.small-button td a:visited, table.medium-button:hover td a, table.medium-button:active td a, table.medium-button td a:visited, table.large-button:hover td a, table.large-button:active td a, table.large-button td a:visited {
        color: #ffffff!important;
    }
    table.secondary td {
        background: #e9e9e9;
        border-color: #d0d0d0;
        color: #555;
    }
    table.secondary td a {
        color: #555;
    }
    table.secondary:hover td {
        background: #d0d0d0!important;
        color: #555;
    }
    table.secondary:hover td a, table.secondary td a:visited, table.secondary:active td a {
        color: #555!important;
    }
    table.success td {
        background: #5da423;
        border-color: #457a1a;
    }
    table.success:hover td {
        background: #457a1a!important;
    }
    table.alert td {
        background: #c60f13;
        border-color: #970b0e;
    }
    table.alert:hover td {
        background: #970b0e!important;
    }
    table.radius td {
        -webkit-border-radius: 3px;
        -moz-border-radius: 3px;
        border-radius: 3px;
    }
    table.round td {
        -webkit-border-radius: 500px;
        -moz-border-radius: 500px;
        border-radius: 500px;
    }
    body.outlook p {
        display: inline!important;
    }
    @media only screen and (max-width: 600px)  {
        table[class="body"] img {
            width: auto!important;
            height: auto!important;
        }
        table[class="body"] center {
            min-width: 0!important;
        }
        table[class="body"] .container {
            width: 95%!important;
        }
        table[class="body"] .row {
            width: 100%!important;
            display: block!important;
        }
        table[class="body"] .wrapper {
            display: block!important;
            padding-right: 0!important;
        }
        table[class="body"] .columns, table[class="body"] .column {
            table-layout: fixed!important;
            float: none!important;
            width: 100%!important;
            padding-right: 0px!important;
            padding-left: 0px!important;
            display: block!important;
        }
        table[class="body"] .wrapper.first .columns, table[class="body"] .wrapper.first .column {
            display: table!important;
        }
        table[class="body"] table.columns td, table[class="body"] table.column td {
            width: 100%!important;
        }
        table[class="body"] .columns td.one, table[class="body"] .column td.one {
            width: 8.333333%!important;
        }
        table[class="body"] .columns td.two, table[class="body"] .column td.two {
            width: 16.666666%!important;
        }
        table[class="body"] .columns td.three, table[class="body"] .column td.three {
            width: 25%!important;
        }
        table[class="body"] .columns td.four, table[class="body"] .column td.four {
            width: 33.333333%!important;
        }
        table[class="body"] .columns td.five, table[class="body"] .column td.five {
            width: 41.666666%!important;
        }
        table[class="body"] .columns td.six, table[class="body"] .column td.six {
            width: 50%!important;
        }
        table[class="body"] .columns td.seven, table[class="body"] .column td.seven {
            width: 58.333333%!important;
        }
        table[class="body"] .columns td.eight, table[class="body"] .column td.eight {
            width: 66.666666%!important;
        }
        table[class="body"] .columns td.nine, table[class="body"] .column td.nine {
            width: 75%!important;
        }
        table[class="body"] .columns td.ten, table[class="body"] .column td.ten {
            width: 83.333333%!important;
        }
        table[class="body"] .columns td.eleven, table[class="body"] .column td.eleven {
            width: 91.666666%!important;
        }
        table[class="body"] .columns td.twelve, table[class="body"] .column td.twelve {
            width: 100%!important;
        }
        table[class="body"] td.offset-by-one, table[class="body"] td.offset-by-two, table[class="body"] td.offset-by-three, table[class="body"] td.offset-by-four, table[class="body"] td.offset-by-five, table[class="body"] td.offset-by-six, table[class="body"] td.offset-by-seven, table[class="body"] td.offset-by-eight, table[class="body"] td.offset-by-nine, table[class="body"] td.offset-by-ten, table[class="body"] td.offset-by-eleven {
            padding-left: 0!important;
        }
        table[class="body"] table.columns td.expander {
            width: 1px!important;
        }
        table[class="body"] .right-text-pad, table[class="body"] .text-pad-right {
            padding-left: 10px!important;
        }
        table[class="body"] .left-text-pad, table[class="body"] .text-pad-left {
            padding-right: 10px!important;
        }
        table[class="body"] .hide-for-small, table[class="body"] .show-for-desktop {
            display: none!important;
        }
        table[class="body"] .show-for-small, table[class="body"] .hide-for-desktop {
            display: inherit!important;
        }
    }
</style>
<style>
    .template-label {
        color: #ffffff;
        font-weight: bold;
        font-size: 11px;
    }
    .callout .panel {
        background: #ECF8FF;
        border-color: #b9e5ff;
    }
    .header {
        background: #8a8a8a;
        box-shadow: 0 2px 12px rgba(120,120,120,0.6)
    }
    .footer .wrapper {
        background: #ebebeb;
    }
    .footer h5 {
        padding-bottom: 10px;
    }
    table.columns .text-pad {
        padding-left: 10px;
        padding-right: 10px;
    }
    table.columns .left-text-pad {
        padding-left: 10px;
    }
    table.columns .right-text-pad {
        padding-right: 10px;
    }
    @media only screen and (max-width: 600px)  {
        table[class="body"] .right-text-pad {
        padding-left: 10px!important;
        }
        table[class="body"] .left-text-pad {
            padding-right: 10px!important;
        }
    }
</style>
<style>
    .template-label {
        color: #ffffff;
        font-weight: bold;
        font-size: 11px;
    }
    .callout .panel {
        background: #cbcbcb;
        border-color: #b9e5ff;
    }
    .header {
        background: #8a8a8a;
        box-shadow: 0 2px 5px rgba(120,120,120,0.6)
    }
    .footer .wrapper {
        background: #ebebeb;
    }
    .footer h5 {
        padding-bottom: 10px;
    }
    .reply-notice {
        background-color: #8cc641;
        font-weight: 900;
    }
    table.columns .text-pad {
        padding-left: 10px;
        padding-right: 10px;
    }
    table.columns .left-text-pad {
        padding-left: 10px;
    }
    table.columns .right-text-pad {
        padding-right: 10px;
    }
    @media only screen and (max-width: 600px)  {
        table[class="body"] .right-text-pad {
        padding-left: 10px!important;
        }
        table[class="body"] .left-text-pad {
            padding-right: 10px!important;
        }
    }
</style>
</head>
<body>
    <table class="body">
        <tr>
            <td class="center" align="center" valign="top">
                <center>
                    <table class="row header">
                        <tr>
                            <td class="center" align="center">
                                <center>
                                    <table class="container">
                                        <tr>
                                            <td class="wrapper last">
                                                <table class="twelve columns">
                                                    <tr>
                                                        <td class="six sub-columns">
                                                            <a href="$ownurl"><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFoAAAAyCAYAAADcD8w1AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAAsTAAALEwEAmpwYAAAIpElEQVR42u2bf3AUZxnHP7t7ubtcfickGyAS2kBIKxakQC0/rGKZsUhBsVg7bZVS2lpRiw461lpnHIf+VajFsWNlqFP5gwIpVK1gqYWCU5yxLZEabNICQoBAAoQQLiF3t7uvfzzvwc1J0isGDi73nXln97K3b/b97rPPfp/v+x5kcUVgDUAfpcBCwACOASrdg8pUzAbOAfVAbrov5mqFOQB9DAOCwGkgku4BXa0YCKLj6ScCeOke0NWKgSDa0Ntsbu4HyUTfACwBxnyMPgr0tjvdg7mWMB/oBPYA01I85/PARmBWui/+WkIu8DXgENAA3JTieUE+XhrKAaqAGcBi4LvAqHQP/nLC6OPv84HnEbK/ARxNOBYEhgPXAyXIC/AMcAJRHp1AGHCT+vQBnwEm6e14hOwAEAPWAN8DetNNyuWAr4+/vwIUAnOBcoToscAcYKret/X5HhBFtPRZhPC9wF+AbcBJ3Wc+8H3gTiSf7wN+D7yj+z9ABstDo59jJpCHkDcT+BXykgxrUhqA94HwnDsDn62oMKe9/XbsSPMHbqS3V9nIDWoCVgF/BE4B1wE3A0cQojvISsLzCADrEfn2KpJX7cMt5XVK2Y8pVVmrPPsp5dpOrLfiyMm28he+szg0AYn+PyBkvgncjUR1Fn2gANiJEH0PgHJslGM/qhzbU469Qzn2Sr2vlGv3Ks9+XqnK++s3FNf6c5gH/BXJ3ZuAyfT/JGUkUlEKFqISHCSNAFyPxRBMDAwmYlJGXEcrAngswlWrvjovsDYSrRy9YkXBI8CPgAnAOiTas0iCDfwTUQMzlBo6Snn2Pw4eGHK46d9l3vHWctW0t+xN5dityrOVcv6nOcq1lys1vCgUMmYi0nEfQvqggS+F7wSBEBCpqbFwo+4POjrUhJ8+GbbCYUVenkF7u1e95sWiXsdRVA6zsEwSC3ILxUO4zqTucMW2uhtObWxudpYADyH62Uk3CVcCqfjRw4BFgDdtqn9TU7P74NGj7tDOTsWOnVHG1FpEovg2b4moDRsi+SOrLcrLTfwBI5HsAFCNydSxN/oiL62LlLou5cjL8ky6SbgSSIXokcCDQNeYWt+alhZ35m23BaoWLszFti0WLMil45TK8TzU2bDyr17daxzY7zJ+vI/CYjPZarLy84zhm7dE/G1tXi6wGUklGY9UUkcJEpFdP1waqn3ttWhNJKIoKTNZuCgXPFi6NIRS9DQ2OqFdu2K+PXscXt8apbjY4I4vBggGDQAXAyJR5VdCvscgknupqI5StLE/epSvqrjYGHKuR4epCygI+A0jGDQKJ07OYe6cAHV1Fi9vjNDY6GAYekLAoDV8Vr3y3HPnYu83OSCR/J90E3ClkEpElyG6tyM/3+jwPJRK1sEmdHer4Mv1vWzbFmXSpBxW/rKAqk+Y+P3Gdkw2HzrolkyffnpEW7tnxGKcMQyeVgoHmAL0IKV7B1LKZxxSIbpSb9tDIeN4uFtFq6qM4PmjJhw/5rF8ebfpuvD4j/OorfNhGIAihknL8OEn32htdZ9ADKow8HOlqAeeRfyUGGJIHQT+BewG3gU+JENUyUcRbQHVev+o56mT7e1eZOoUTbQFBw+4LFvW7dTVWca3Hg1ZeXnGefci5vC7WbNO725tddcgZlQL8DNgrSZwBfAeUn1WADWI6fRN5Ib8BngauREZjQLEp1DAfW/tLLlx7pxA+56GMqWUrRreLVVzZgeO3TzB9+S5nopNyrVjyrG7lLLPdnZUqCWPhd4BDiPZfDswnb7LbwPR6yOAzyFO33xSe+queVQD+5HSe9r4cb5Pzf5S4MSJ9nL1xtYSNeXWnGYkAk2lKiuUsh+Ixey71q0tWjb/rmBvMGgooAtYjujxLPrALUhBcQgx+u/+wgz/nzfWF+29956g+5PH8xbXry8CUS+lyPTXMqAZeQo+AO5H5OGgxke5aLcgXnILMic40u8nMqbWV/PIw7k3fbjPfevZlT2ViHKYjPjV+Yh6eBXJwXvSPcirAf0R7UPm8cYiFud2JNeWItNcVUg6qEKi9wTQCPwNeB0xojJSql0K+nvR1AAvIAT+FtHTOUga2AI8gEw9rQJ2ICQfRNRCdo1HEvojOojM500DXgRaEaItZI5vPRe8iozQupcT/RH9deAOYDUSofOQ/BsB/Mic4BGyJKeE/ty7s8DtyGrRMiTC8xGF8RLwDNkcnDL6M5X2I7PcJYiqGI2UyU1IGsnI9RdXGp9EZF07UnDsBB5GfI8Qg3By9f/FxXL0SODXyAvvy0jKaECiOYsBQgAxcrYCQ9N9MZmM2Uj5PCPdF5LJKEbWyz3DIHHM0oXbEZXx6XRfSCYiMXLLEF18fAD7t5DiJogsmMxHVqmGkLXYuUi16UOkpqnPiZ/n09t46e/XzdLflXkcaZ5uLjJRkNiiiBztQVZUdSGuZJduYX08xmWyDxKJbtT/7D7gT4gD14tUfkoPytCD9OnBhzRxRZrEAkR3lyCpqEQfy00gyNH9RhJIcTg/1YvS+4mERTRZ3Rf5fhxmQvMlXGeuvoZgUgvoMSjdZxhZ8dqGKK6jyO8mT+qbcrH13oU6gBzEeOuzgDOS9iciCxlH6M8uF0psI2EQ8YHECx5XkxdGKspOfaMSW6cmqocL0eNxIRpJIE5xeSIr8UbkaJIK9I2oQJa/DdPbYiSQXE32AcRf3wcMAe4FanU/UcR8a0AMt0aSliNfrPDwIVZoub5j8TsfJ9TRJHUnERfVLf4EXMswkagvRIq0Gk3qdfrzOGAX8iPWw/qc+NrvOkQib073IK5lWIhYaEAW5yfDAH6BGHGB5BOzSB0KyeEm8BVkacSphOPjkFn+auQpKERs5GiW6EvDe4hK+zaS508h6XUZ8n57ArEsxiC/5+nKmkOXDhO4FViATOflID7R3xGf/ikuLNzPunADgCAytzoaiezdiGJpYxAs/Lnq8F+q799xspLOEgAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAxNi0wMS0zMVQyMjowODoyMiswMTowMN17DyEAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMTQtMTEtMTJUMjI6MzY6MzkrMDE6MDBTY2O4AAAAAElFTkSuQmCC"></a>
                                                        </td>
                                                        <td class="six sub-columns last" align="right" style="text-align:right; vertical-align:middle;">
                                                            <a href="$ownurl"><span class="template-label">$site</span></a>
                                                        </td>
                                                        <td class="expander"></td>
                                                    </tr>
                                                </table>
                                            </td>
                                        </tr>
                                    </table>
                                </center>
                            </td>
                        </tr>
                    </table>
                    <br>
                    <table class="container">
                        <tr>
                            <td>
                                <table class="row">
                                    <tr>
                                        <td class="wrapper last">
                                            <table class="twelve columns">
                                                <tr>
                                                    <td>
                                                        <h1>Hello, $ownname</h1>
                                                        <p class="lead">you have been contacted by <strong>$dnxcf_name</strong> on <strong>$site</strong></p>
                                                    </td>
                                                    <td class="expander"></td>
                                                </tr>
                                            </table>
                                        </td>
                                    </tr>
                                </table>
                                <table class="row callout">
                                    <tr>
                                        <td class="wrapper last">
                                            <table class="twelve columns">
                                                <tr>
                                                    <td class="panel">
                                                        <p>Some details about $dnxcf_name:
                                                            <ul>
                                                                <li>Browser: $ua</li>
                                                                <li>Time: $time</li>
                                                                <li>IP Address: $host</li>
                                                            </ul>
                                                        </p>
                                                    </td>
                                                    <td class="expander"></td>
                                                </tr>
                                            </table>
                                        </td>
                                    </tr>
                                </table>
                                <table class="row">
                                    <tr>
                                        <td class="wrapper last">
                                            <table class="twelve columns">
                                                <tr>
                                                    <td>
                                                        <h3>message about <strong>"$dnxcf_subject"</strong></h3>
                                                        <p>$dnxcf_message</p>
                                                    </td>
                                                    <td class="expander"></td>
                                                </tr>
                                            </table>
                                        </td>
                                    </tr>
                                </table>
                                <table class="row">
                                    <tr>
                                        <td class="wrapper last">
                                            <table class="twelve columns">
                                                <tr>
                                                    <td align="center">
                                                        <center>
                                                            <p class="reply-notice" style="text-align:center;"><small>you can reply directly to this email</small></p>
                                                        </center>
                                                    </td>
                                                    <td class="expander"></td>
                                                </tr>
                                            </table>
                                        </td>
                                    </tr>
                                </table>
                                <table class="row">
                                    <tr>
                                        <td class="wrapper last">
                                            <table class="twelve columns">
                                                <tr>
                                                    <td align="center">
                                                        <center>
                                                            <p style="text-align:center;"><a href="http://danixland.net/?p=3577">author support</a> | <a href="https://wordpress.org/support/">WordPress Support Forum</a></p>
                                                        </center>
                                                    </td>
                                                    <td class="expander"></td>
                                                </tr>
                                            </table>
                                        </td>
                                    </tr>
                                </table>
                            </td>
                        </tr>
                    </table>
                </center>
            </td>
        </tr>
    </table>
</body>
</html>

DNX44665312EOT;

    return $output;

}

?>

